/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ka266.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {

  final TextPlayer player1;
  final TextPlayer player2;

  public App(TextPlayer player1, TextPlayer player2) {
    this.player1 = player1;
    this.player2 = player2;
  }

  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public static void main(String[] args) throws IOException {


    
     Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
     Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
     BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
     V1ShipFactory factory = new V1ShipFactory();
     TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);

     p1.doPlacementPhase();
     /**
      * TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
     * 
     * App app = new App(p1, p2);
     * 
     * app.doPlacementPhase();
     * 
     * while (true) {
     * // Player 1 Turn
     * p1.playOneTurn(p2.theBoard, p2.view, p2.TextPlayer);
     * if (p2.checkLost()) {
     * System.out.print("Player "+ p2.TextPlayer+" Lost!\n");
     * break;
     * }
     * 
     * // Player 2 turn
     * p2.playOneTurn(p1.theBoard, p1.view, p1.TextPlayer);
     * if (p1.checkLost()) {
     * System.out.print("Player "+ p1.TextPlayer +" Lost!\n");
     * break;
     * }
     * }
     **/
  }
}
